version: '3.8'

services:
  dbdevllm:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coucou
      MYSQL_DATABASE: mydbdev
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - llm-net-dev
      
  jupyterlab:
    image: hstubbe/llm-notebook
    restart: always
    ports:
      - 10000:8888
    networks:
      - llm-net-dev
    user: root
    volumes:
      - ${DOCKER_DATA_PATH}/:/data
      - ${DOCKER_DATA_PATH_2}/:/data2
      # Define DOCKER_DATA_PATH and DOCKER_DATA_PATH_2 environment variables before running docker-compose
      # Example .env (Linux):
      # DOCKER_DATA_PATH=[/path/to/your/data]
      # DOCKER_DATA_PATH_2=[/path/to/your/data2]
      # UID=1000
      # GID=1000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      
networks:
  llm-net-dev:
    external: false