# Use root/example as user/password credentials
version: '3.5'

services:
  dbdevdanjgo:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=userdanjgo
      - POSTGRES_PASSWORD=userdanjgo
      - POSTGRES_DB=mydbdevdanjgo
    networks:
      - sp-net-dev-danjgo
            

  jupyterlabdanjgo:
    image: hstubbe/dj-tf-notebook:postgres
    restart: always
    ports:
      - 7070:8888
      - 5050:8000
    networks:
      - sp-net-dev-danjgo
    user: jovyan
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: bash -c "start.sh jupyter lab"
      

  rstudiodanjgo:
    image: hstubbe/rstudio4dev:latest
    restart: always
    environment:
      PASSWORD: test123
      ADD: shiny
    ports:
      - 6060:8787
    networks:
      - sp-net-dev-danjgo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      

networks:
  sp-net-dev-danjgo:
    external: false