# Use root/example as user/password credentials
version: '3.5'

services:
  dbdevllm:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coucou
      MYSQL_DATABASE: mydbdev
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - llm-net-dev
      
  jupyterlab:
    image: hstubbe/llm-notebook
    restart: always
    ports:
      - 10000:8888
    networks:
      - llm-net-dev
    user: jovyan
    volumes:
      - ${DOCKER_DATA_PATH}/:/home/jovyan/home
      - ${DOCKER_DATA_PATH_2}/:/home/jovyan/home2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash -c "start.sh jupyter lab"
      

networks:
  llm-net-dev:
    external: false