# Use root/example as user/password credentials
version: '3.5'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coucou
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - sp-net-dev
      
  rstudio:
    image: rstudio4test
    restart: always
    environment:
      PASSWORD: test123
      ADD: shiny
    ports:
      - 9090:8787
    networks:
      - sp-net-dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      
networks:
  sp-net-dev:
    external: false