# Use root/example as user/password credentials
version: '3.5'

services:
  dbdev:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coucou
      MYSQL_DATABASE: mydbdev
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - sp-net-dev
      
  rstudio:
    image: hstubbe/rstudio4dev:latest
    restart: always
    environment:
      PASSWORD: test123
      ADD: shiny
    ports:
      - 9090:8787
    networks:
      - sp-net-dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      
  jupyterlab:
    image: hstubbe/nanopore-notebook
    restart: always
    ports:
      - 10000:8888
    networks:
      - sp-net-dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash -c "start.sh jupyter lab"
      

networks:
  sp-net-dev:
    external: false