# Use root/example as user/password credentials
version: '3.5'

services:

  rstudio:
    image: rocker/rstudio:latest
    restart: always
    environment:
      PASSWORD: test123
      ADD: shiny
    ports:
      - 9090:8787
    networks:
      - sp-net-dev
    volumes:
      - ${DOCKER_DATA_PATH}/:/home/rstudio
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      
  jupyterlab:
    image: jupyter/tensorflow-notebook
    restart: always
    ports:
      - 10000:8888
    networks:
      - sp-net-dev
    volumes:
      - ${DOCKER_DATA_PATH}/:/home/jovyan/home
    user: jovyan
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: bash -c "start.sh jupyter lab"
      

networks:
  sp-net-dev:
    external: false